services:
  - docker

install:
  - docker-compose -f docker-compose.install.yml up
  - docker-compose -f docker-compose.install.yml run composer composer require php-coveralls/php-coveralls
  - docker-compose down
  - docker-compose up -d
  - sleep 30
  - docker exec wsapp cp .env.travis .env
  - docker exec wsapp php artisan key:generate
  - docker exec wsapp php artisan migrate
  - docker exec wsapp php artisan passport:install
  - docker-compose stop

script:
  - docker-compose run -e WEBLING_API_KEY=${WEBLING_API_KEY} -e WEBLING_BASE_URL=${WEBLING_BASE_URL} app php /var/www/html/vendor/phpunit/phpunit/phpunit --configuration /var/www/html/phpunit.xml --coverage-clover /var/www/html/build/logs/clover.xml

after_success:
  - travis_retry docker-compose run -e TRAVIS=${TRAVIS} -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID} app php /var/www/html/vendor/bin/php-coveralls -v

notifications:
  email: false
  slack:
    secure: fjnK3LV5+yI+B9zug9iLIwh/5d42O+Pc/gsqBtGjzGzkZrEPxhz5qektXXiZ+HdJ9s/Y5f0N5Pe4/HD8QQXn4jD1VirE7S7mUZGk7lJPeJPAohmL6ii1j1xR3tVNwfNgugIOtzqx8h2CMlCghQPU1leCU0b4fiHAF714Sf40nqJ29R5kVXnrz+FXQvgwJ95CATJDJ8zFbr9qVNg2l1aru742I/m6W7XEP6TY1zxHlvtJ4e1RL+01xNv9oikNKgrDhemxZxYdMgHkqfnBD8OwEoP7R2I3BtKIXnQXtLQc6q4z5E6G8UGbzSVSJ1QKGrQ9kWQ7+Qj0vyx9paFTUqQ+h3h+nlvug5lAE3xc7pDiOQnlucMrgSOOL+oT7Z6mRWBKxVvL56t0Fi4DCtGhczRpvxsXKAAyG91d2R5uX16d82qMgBSwVg1pa3twdD8UeoAKLpGJg8xyLKDdYxa8ByATLKrlZ32XjF3EONdI0S/u6u1FYKWUV2hjVaY/l5TR3ChFftgLZgyQX59mR7WzvQkwpBGeB18lxwjv4j959nnF5KFxkUqpr1vSrVHDf05jqiJdS+nFL3AoP04JSQCKedLbbaB8Sd77UlpyW0vVC4GhqvOxNISxEeus+3O1mjscXHrLpRrNai3neh7+n6PgWir8LpqCwLhJlYHiyLo4xbe7CS4=
