version: '3'

services:
  weblingservice:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - .docker/php.ini:/usr/local/etc/php/php.ini
      - .docker/apache-vhost.conf:/etc/apache2/sites-available/custom-vhost.conf
    container_name: wsapp
    environment:
        DB_HOST: mysql
        DB_DATABASE: laravel
        DB_USERNAME: laravel
        DB_PASSWORD: laravel
        DB_PORT: 3306
        # play with mailhog
        MAIL_HOST: mailhog
        MAIL_PORT: 1025
        MAIL_USERNAME: null
        MAIL_PASSWORD: null
        MAIL_ENCRYPTION: null
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gruene-services-bridge-network

  mysql:
    image: mysql:5.7
    ports:
        - '3307:3306'
    volumes:
        - database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
    container_name: wsmysql_webling
    networks:
      - gruene-services-bridge-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8010:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_PORT: '3306'
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    container_name: wsphpmyadmin_webling
    networks:
      - gruene-services-bridge-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8020:8025'
    container_name: wsmailhog_webling
    networks:
      - gruene-services-bridge-network

volumes:
  database:

networks:
  gruene-services-bridge-network:
    external: true
