mappings:
  - email1
  - firstName
  - lastName
  - gender
  - recordCategory
  - emailStatus
  - language
  - city
  - newsletterCountryD
  - newsletterCountryF
  - newsletterCantonD
  - newsletterCantonF
  - newsletterMunicipality
  - newsletterOther
  - pressReleaseCountryD
  - pressReleaseCountryF
  - pressReleaseCantonD
  - pressReleaseCantonF
  - pressReleaseMunicipality
  - memberStatusCountry
  - memberStatusCanton
  - memberStatusRegion
  - memberStatusMunicipality
  - membershipStart
  - interests
  - donorCountry
  - donorCanton
  - donorRegion
  - donorMunicipality
  - notesCountry
  - notesCanton
  - notesMunicipality
  - recordCategory
  - recordStatus