mappings:
  - email1
  - firstName
  - lastName
  - gender
  - recordCategory
  - emailStatus
  - language
  - newsletterCountryD
  - newsletterCountryF
  - newsletterMunicipality
  - newsletterOther
  - pressReleaseCountryD
  - pressReleaseCountryF
  - memberStatusCountry
  - interests
  - donorCountry
  - notesCountry
  - recordCategory
  - recordStatus
